FROM nginx:latest   

WORKDIR /usr/share/nginx/html/

COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./site1.conf /etc/nginx/conf.d/site1.conf

# RUN apt-get update && apt-get install -y git && apt-get install -y nano  && apt-get install php7.4-fpm -y
# RUN git clone https://alastrols:MHvFfJapGVYxkMRBRyDK@bitbucket.org/itp-it/aica-website.git
# RUN rm -rf html
# RUN ls
# RUN mv aica-website html && mv html/* .
# RUN rm -rf html

# RUN cd /usr/share/nginx/html/
# RUN rm -rf aica-website